Pass parameters to bs-button from bs-dropdown-button
ember-bootstrap/ember-bootstrap pull request #2129
Opened 2024-05-27 13:32 UTC by zfir

CSS not applied when using `@type` parameter on `bs-dropdown-button`

2024-05-28 06:44 UTC, jelhan requested changes
Thanks a lot for fixing this bug! I likely introduced it in #2111. 😬

I have two change requests from review. Additionally Prettier complains about template syntax. Would be great if you could fix those.

2024-05-28 06:44 UTC, jelhan commented on test-app/tests/integration/components/bs-dropdown/button-test.js
> +      hbs`<BsDropdown as |dd|><dd.button @outline="true">Test</dd.button></BsDropdown>`,
It should be `true` as a boolean value. Not a string.

```suggestion
      hbs`<BsDropdown as |dd|><dd.button @outline={{true}}>Test</dd.button></BsDropdown>`,
```

2024-05-28 06:44 UTC, jelhan commented on ember-bootstrap/addon/components/bs-dropdown/button.hbs
> +  @active={{@active}}
`@active` argument does not seem to be covered by tests. Do you mind adding tests for it?

2024-05-28 07:18 UTC, jelhan commented on test-app/tests/integration/components/bs-dropdown/button-test.js
> +      hbs`<BsDropdown as |dd|><dd.button @type="primary">Test</dd.button></BsDropdown>`,
Make Prettier happy:

```suggestion
      hbs`<BsDropdown as |dd|><dd.button @type='primary'>Test</dd.button></BsDropdown>`,
```

2024-05-28 07:20 UTC, jelhan requested changes
Two syntax changes required to make Prettier happy. I'm not sure why it enforces single code for inline templates. It should not. But that's the case for all tests currently. So nothing to be addressed here.

2024-05-28 07:20 UTC, jelhan commented on test-app/tests/integration/components/bs-dropdown/button-test.js
> +      hbs`<BsDropdown as |dd|><dd.button @size="lg">Test</dd.button></BsDropdown>`,
Prettify the inline template:

```suggestion
      hbs`<BsDropdown as |dd|><dd.button @size='lg'>Test</dd.button></BsDropdown>`,
```

2024-05-28 09:16 UTC, jelhan approved these changes

2024-05-31 16:14 UTC, simonihmig approved these changes
Thank you @zfir! :pray:

> CI should be fixed by https://github.com/ember-bootstrap/ember-bootstrap/pull/2130. Would prefer to land that one and fix CI before merging this. Just to make sure that we don't miss something.

Just merged that. @zfir would you mind rebasing your PR, that should then hopefully turn it fully green!

2024-05-31 16:14 UTC, simonihmig commented on test-app/tests/integration/components/bs-dropdown/button-test.js
> +  test('dropdown button has coorect css type class', async function (assert) {
very minor typo here :)

2024-05-31 16:20 UTC, zfir commented
> Thank you @zfir! 🙏
> 
> > CI should be fixed by #2130. Would prefer to land that one and fix CI before merging this. Just to make sure that we don't miss something.
> 
> Just merged that. @zfir would you mind rebasing your PR, that should then hopefully turn it fully green!

@simonihmig just done can you check

2024-05-31 17:32 UTC, merged

2024-06-14 07:35 UTC, zfir commented
@jelhan @simonihmig Can we publish a version for this? Thanks

2024-07-03 11:24 UTC, zfir commented
Hello @jelhan @simonihmig,

Is there a version that has been published?

2024-07-03 13:11 UTC, jelhan commented
I just released it as [v6.3.2](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.3.2). I'm sorry for the delay.